stages:
- name: build
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:foo-v2-docker-registry
      version: 1.9.2
      name: test-pipe-bbb
      targetNamespace: aaa
notification: {}
