stages:
- name: build
  steps:
  - publishCatalogConfig:
      path: ./mysql/v0.3.7
      catalogTemplate: mysql
      version: foo-1.0.0+build5
      gitUrl: https://github.com/rootwuj/wujing-catalog-test.git
      gitBranch: master
      gitAuthor: wuj
      gitEmail: wuj@aa.com
    envFrom:
    - sourceName: test-pipeline
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: test-pipeline
      sourceKey: PASSWORD
      targetKey: PASSWORD
notification: {}
