stages:
- name: test
  steps:
  - publishCatalogConfig:
      path: ./wordpress/v1.0.5
      catalog: wordpress
      version: v1.0.5
      gitUrl: https://github.com/rootwuj/test-catalog-custom.git
      gitBranch: master
      gitAuthor: wujing
      gitEmail: jing@rancher.com
    envFrom:
    - sourceName: s-9dz92
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: s-9dz92
      sourceKey: PASSWORD
      targetKey: PASSWORD
timeout: 60
notification: {}
