stages:
- name: build
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:aaa-docker-registry
      version: 1.8.1
      name: test-pipe-aaa
      targetNamespace: aaa
notification: {}
