stages:
- name: test
  steps:
  - applyAppConfig:
      catalog: bbb
      version: 2.1.10
      name: bbb-wordpress
      targetNamespace: aaa
- name: test02
  steps:
  - applyAppConfig:
      catalog: bbb
      version: 2.1.10
      name: bbb-wordpress
      targetNamespace: aaa
timeout: 60
notification: {}
