stages:
- name: test02
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: nginx
- name: test03
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
